### ISSUE TITLE
Internet.user_name always returning the same 4 values

### ISSUE THREAD

**Issue by watzon** [askn/faker#10]
The `Faker::Internet.user_name` method is always returning the same 4 values:

- faker.internet
- faker_internet
- internet.faker
- internet_faker

**Comment by jwoertink** [comment]
Just ran in to this 😝

**Comment by jwoertink** [comment]
Looks like it's this line https://github.com/askn/faker/blob/master/src/faker/internet.cr#L49 which is calling `name` on the class `Faker::Internet.name`. There's a catch in there `if name`, but `name` always exists. My guess is that line was meant to look at a different variable 🤔
